### ISSUE TITLE
Unable to run on Mac OS

### ISSUE THREAD

**Issue by BlackRider97** [pinterest/thrift-tools#9]
```
$ thrift-tool 
Traceback (most recent call last):
  File "/usr/local/bin/thrift-tool", line 11, in <module>
    from thrift_tools.tool import main
  File "/Library/Python/2.7/site-packages/thrift_tools/tool.py", line 13, in <module>
    from .message_sniffer import MessageSnifferOptions, MessageSniffer
  File "/Library/Python/2.7/site-packages/thrift_tools/message_sniffer.py", line 8, in <module>
    from .sniffer import Sniffer
  File "/Library/Python/2.7/site-packages/thrift_tools/sniffer.py", line 13, in <module>
    from scapy.sendrecv import sniff
  File "/Library/Python/2.7/site-packages/scapy/sendrecv.py", line 13, in <module>
    import arch
  File "/Library/Python/2.7/site-packages/scapy/arch/__init__.py", line 75, in <module>
    from bsd import *
  File "/Library/Python/2.7/site-packages/scapy/arch/bsd.py", line 12, in <module>
    from unix import *
  File "/Library/Python/2.7/site-packages/scapy/arch/unix.py", line 20, in <module>
    from pcapdnet import *
  File "/Library/Python/2.7/site-packages/scapy/arch/pcapdnet.py", line 30, in <module>
    import pcapy as pcap
ImportError: No module named pcapy
```

while It was installed  successfully 
```
$ sudo pip install thrift-tools
Collecting thrift-tools
  Downloading thrift-tools-0.0.3.tar.gz
Collecting ansicolors (from thrift-tools)
  Downloading ansicolors-1.0.2.tar.gz
Collecting dpkt (from thrift-tools)
  Downloading dpkt-1.9.1-py2-none-any.whl (136kB)
    100% |################################| 139kB 632kB/s 
Collecting scapy==2.3.1 (from thrift-tools)
  Downloading scapy-2.3.1.zip (1.1MB)
    100% |################################| 1.1MB 565kB/s 
Collecting thrift==0.9.2 (from thrift-tools)
  Downloading thrift-0.9.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): tabulate in /Library/Python/2.7/site-packages (from thrift-tools)
Installing collected packages: thrift, scapy, dpkt, ansicolors, thrift-tools
  Found existing installation: thrift 0.9.3
    Uninstalling thrift-0.9.3:
      Successfully uninstalled thrift-0.9.3
  Running setup.py install for thrift
    building 'thrift.protocol.fastbinary' extension
    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/protocol/fastbinary.c -o build/temp.macosx-10.10-intel-2.7/src/protocol/fastbinary.o
    src/protocol/fastbinary.c:114:11: warning: 'ntohll' macro redefined [-Wmacro-redefined]
    #  define ntohll(n) ( (((unsigned long long)ntohl(n)) << 32) + ntohl(n >> 32) )
              ^
    /usr/include/sys/_endian.h:140:9: note: previous definition is here
    #define ntohll(x)       __DARWIN_OSSwapInt64(x)
            ^
    src/protocol/fastbinary.c:115:11: warning: 'htonll' macro redefined [-Wmacro-redefined]
    #  define htonll(n) ( (((unsigned long long)htonl(n)) << 32) + htonl(n >> 32) )
              ^
    /usr/include/sys/_endian.h:141:9: note: previous definition is here
    #define htonll(x)       __DARWIN_OSSwapInt64(x)
            ^
    src/protocol/fastbinary.c:226:24: warning: implicit conversion loses integer precision: 'long' to 'TType' (aka 'enum TType') [-Wshorten-64-to-32]
      dest->element_type = PyInt_AsLong(PyTuple_GET_ITEM(typeargs, 0));
                         ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/protocol/fastbinary.c:227:7: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
      if (INT_CONV_ERROR_OCCURRED(dest->element_type)) {
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/protocol/fastbinary.c:124:43: note: expanded from macro 'INT_CONV_ERROR_OCCURRED'
    #define INT_CONV_ERROR_OCCURRED(v) ( ((v) == -1) && PyErr_Occurred() )
                                          ~~~ ^  ~~
    src/protocol/fastbinary.c:243:16: warning: implicit conversion loses integer precision: 'long' to 'TType' (aka 'enum TType') [-Wshorten-64-to-32]
      dest->ktag = PyInt_AsLong(PyTuple_GET_ITEM(typeargs, 0));
                 ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/protocol/fastbinary.c:244:7: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
      if (INT_CONV_ERROR_OCCURRED(dest->ktag)) {
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/protocol/fastbinary.c:124:43: note: expanded from macro 'INT_CONV_ERROR_OCCURRED'
    #define INT_CONV_ERROR_OCCURRED(v) ( ((v) == -1) && PyErr_Occurred() )
                                          ~~~ ^  ~~
    src/protocol/fastbinary.c:248:16: warning: implicit conversion loses integer precision: 'long' to 'TType' (aka 'enum TType') [-Wshorten-64-to-32]
      dest->vtag = PyInt_AsLong(PyTuple_GET_ITEM(typeargs, 2));
                 ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/protocol/fastbinary.c:249:7: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
      if (INT_CONV_ERROR_OCCURRED(dest->vtag)) {
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/protocol/fastbinary.c:124:43: note: expanded from macro 'INT_CONV_ERROR_OCCURRED'
    #define INT_CONV_ERROR_OCCURRED(v) ( ((v) == -1) && PyErr_Occurred() )
                                          ~~~ ^  ~~
    src/protocol/fastbinary.c:281:15: warning: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
      dest->tag = PyInt_AsLong(PyTuple_GET_ITEM(spec_tuple, 0));
                ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/protocol/fastbinary.c:286:16: warning: implicit conversion loses integer precision: 'long' to 'TType' (aka 'enum TType') [-Wshorten-64-to-32]
      dest->type = PyInt_AsLong(PyTuple_GET_ITEM(spec_tuple, 1));
                 ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/protocol/fastbinary.c:287:7: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
      if (INT_CONV_ERROR_OCCURRED(dest->type)) {
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/protocol/fastbinary.c:124:43: note: expanded from macro 'INT_CONV_ERROR_OCCURRED'
    #define INT_CONV_ERROR_OCCURRED(v) ( ((v) == -1) && PyErr_Occurred() )
                                          ~~~ ^  ~~
    src/protocol/fastbinary.c:489:22: warning: implicit conversion loses integer precision: 'Py_ssize_t' (aka 'long') to 'int32_t' (aka 'int') [-Wshorten-64-to-32]
        writeI32(output, len);
        ~~~~~~~~         ^~~
    src/protocol/fastbinary.c:740:7: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
      if (INT_CONV_ERROR_OCCURRED(got)) {
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/protocol/fastbinary.c:124:43: note: expanded from macro 'INT_CONV_ERROR_OCCURRED'
    #define INT_CONV_ERROR_OCCURRED(v) ( ((v) == -1) && PyErr_Occurred() )
                                          ~~~ ^  ~~
    src/protocol/fastbinary.c:787:15: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
        if (etype == -1) {
            ~~~~~ ^  ~~
    src/protocol/fastbinary.c:809:15: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
        if (ktype == -1) {
            ~~~~~ ^  ~~
    src/protocol/fastbinary.c:814:15: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
        if (vtype == -1) {
            ~~~~~ ^  ~~
    src/protocol/fastbinary.c:836:16: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
          if (type == -1) {
              ~~~~ ^  ~~
    src/protocol/fastbinary.c:875:22: warning: implicit conversion loses integer precision: 'Py_ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
      int spec_seq_len = PyTuple_Size(spec_seq);
          ~~~~~~~~~~~~   ^~~~~~~~~~~~~~~~~~~~~~
    src/protocol/fastbinary.c:888:14: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
        if (type == -1) {
            ~~~~ ^  ~~
    src/protocol/fastbinary.c:1008:33: warning: implicit conversion loses integer precision: 'Py_ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
        if (!readBytes(input, &buf, len)) {
             ~~~~~~~~~              ^~~
    20 warnings generated.
    src/protocol/fastbinary.c:114:11: warning: 'ntohll' macro redefined [-Wmacro-redefined]
    #  define ntohll(n) ( (((unsigned long long)ntohl(n)) << 32) + ntohl(n >> 32) )
              ^
    /usr/include/sys/_endian.h:140:9: note: previous definition is here
    #define ntohll(x)       __DARWIN_OSSwapInt64(x)
            ^
    src/protocol/fastbinary.c:115:11: warning: 'htonll' macro redefined [-Wmacro-redefined]
    #  define htonll(n) ( (((unsigned long long)htonl(n)) << 32) + htonl(n >> 32) )
              ^
    /usr/include/sys/_endian.h:141:9: note: previous definition is here
    #define htonll(x)       __DARWIN_OSSwapInt64(x)
            ^
    src/protocol/fastbinary.c:227:7: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
      if (INT_CONV_ERROR_OCCURRED(dest->element_type)) {
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/protocol/fastbinary.c:124:43: note: expanded from macro 'INT_CONV_ERROR_OCCURRED'
    #define INT_CONV_ERROR_OCCURRED(v) ( ((v) == -1) && PyErr_Occurred() )
                                          ~~~ ^  ~~
    src/protocol/fastbinary.c:244:7: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
      if (INT_CONV_ERROR_OCCURRED(dest->ktag)) {
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/protocol/fastbinary.c:124:43: note: expanded from macro 'INT_CONV_ERROR_OCCURRED'
    #define INT_CONV_ERROR_OCCURRED(v) ( ((v) == -1) && PyErr_Occurred() )
                                          ~~~ ^  ~~
    src/protocol/fastbinary.c:249:7: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
      if (INT_CONV_ERROR_OCCURRED(dest->vtag)) {
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/protocol/fastbinary.c:124:43: note: expanded from macro 'INT_CONV_ERROR_OCCURRED'
    #define INT_CONV_ERROR_OCCURRED(v) ( ((v) == -1) && PyErr_Occurred() )
                                          ~~~ ^  ~~
    src/protocol/fastbinary.c:287:7: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
      if (INT_CONV_ERROR_OCCURRED(dest->type)) {
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/protocol/fastbinary.c:124:43: note: expanded from macro 'INT_CONV_ERROR_OCCURRED'
    #define INT_CONV_ERROR_OCCURRED(v) ( ((v) == -1) && PyErr_Occurred() )
                                          ~~~ ^  ~~
    src/protocol/fastbinary.c:740:7: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
      if (INT_CONV_ERROR_OCCURRED(got)) {
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/protocol/fastbinary.c:124:43: note: expanded from macro 'INT_CONV_ERROR_OCCURRED'
    #define INT_CONV_ERROR_OCCURRED(v) ( ((v) == -1) && PyErr_Occurred() )
                                          ~~~ ^  ~~
    src/protocol/fastbinary.c:787:15: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
        if (etype == -1) {
            ~~~~~ ^  ~~
    src/protocol/fastbinary.c:809:15: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
        if (ktype == -1) {
            ~~~~~ ^  ~~
    src/protocol/fastbinary.c:814:15: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
        if (vtype == -1) {
            ~~~~~ ^  ~~
    src/protocol/fastbinary.c:836:16: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
          if (type == -1) {
              ~~~~ ^  ~~
    src/protocol/fastbinary.c:888:14: warning: comparison of constant -1 with expression of type 'TType' (aka 'enum TType') is always false [-Wtautological-constant-out-of-range-compare]
        if (type == -1) {
            ~~~~ ^  ~~
    12 warnings generated.
    cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.10-intel-2.7/src/protocol/fastbinary.o -o build/lib.macosx-10.10-intel-2.7/thrift/protocol/fastbinary.so
    /usr/bin/python -O /tmp/tmpnlFZzW.py
    removing /tmp/tmpnlFZzW.py
  Running setup.py install for scapy
    changing mode of build/scripts-2.7/scapy from 644 to 755
    changing mode of build/scripts-2.7/UTscapy from 644 to 755
    changing mode of /usr/local/bin/scapy to 755
    changing mode of /usr/local/bin/UTscapy to 755

  Running setup.py install for ansicolors
  Running setup.py install for thrift-tools
    changing mode of build/scripts-2.7/thrift-tool from 644 to 755
    changing mode of build/scripts-2.7/thrift-file-reader from 644 to 755
    changing mode of /usr/local/bin/thrift-file-reader to 755
    changing mode of /usr/local/bin/thrift-tool to 755
Successfully installed ansicolors-1.0.2 dpkt-1.9.1 scapy-2.3.1 thrift-0.9.2 thrift-tools-0.0.3
```

**Comment by BlackRider97** [comment]
Fixed after following these steps
```
brew install --with-python libdnet
pip install pcapy
pip install scapy
```
It looks like package dependencies is not well defined
